version: 2.1

workflows:
  version: 2
  build-and-cache:
    jobs:
      - build
      - cache:
          context: NIX_BUILD
          requires:
            - build
          filters:
            branches:
              only:
                - master

commands:
  setup-cachix:
    description: Setup Cachix
    steps:
      - run:
          name: Install dependencies
          command: |
            apk --no-progress update
            apk --no-progress add ca-certificates git
            nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run:
          name: Add build caches
          command: |
            cachix use maker
            cachix use dapp

executors:
  nix-executor:
    docker:
      - image: nixos/nix@sha256:af330838e838cedea2355e7ca267280fc9dd68615888f4e20972ec51beb101d8
    working_directory: /root/source

jobs:
  build:
    executor: nix-executor
    steps:
      - setup-cachix
      - checkout
      - run:
          name: Build
          command: nix-build --no-out-link -A makerpkgs
  cache:
    executor: nix-executor
    steps:
      - setup-cachix
      - checkout
      - run:
          name: Push to Cachix
          command: nix-build --no-out-link -A makerpkgs | cachix push maker
